### ISSUE TITLE
BCM94360CS2 using M.2 adapter Bluetooth won't turn on

### ISSUE THREAD

**Issue by SeaDaddytheRed** [zearp/Nucintosh#76] opened 2022-02-05 07:09 UTC
Hello, it's me again.

So I installed a BCM94360CS2 with an M.2 adapter I got off Aliexpress.  It has a USB data and power wire that I plugged into the HS06 head on the motherboard.

I removed the intel kext that I think I should have and added the AirportBrcmFixup kext.

Wifi is working no problem but my Bluetooth won't even turn on.  It just remains in the off state.

I am sorry to bother you with this but I am sure it is an easy fix.

Here is my [config.plist](https://pastebin.com/Eb2f9E4f)

**Comment by SeaDaddytheRed** [comment] 2022-02-05 07:43
Here is my USB maps in Hackintool also.  I have it plugged into the usb header on the right looking from the m.2 slot.

<a href="https://ibb.co/64DNFTc"><img src="https://i.ibb.co/vJLDkTC/Screen-Shot-2022-02-05-at-4-41-44-PM.png" alt="Screen-Shot-2022-02-05-at-4-41-44-PM" border="0"></a>

**Comment by zearp** [comment] 2022-02-05 12:35
The screenshot is not showing any usb bluetooth device. It could be the usb cable might not be seated properly or broken. It should at the very least show a Broadcom device (BRCM20702 hub). The facts the hub is missing tells me either the cable isn't seated properly or the cable might be broken. Check of all wires going into the connected are in there.

If you boot into Windows or Linux does such a usb bluetooth device/hub show up?

The usb map provided by the EFI already has the internal ports mapped. Be sure to disable/remove HS07, this is not needed fort the function for for proper sleep.

As this an Apple branded card it is not needed or advised to use any additional kexts. 

I am using the BCM94360CS2 in a couple of builds and they don't require any additional kexts. It would only be needed to use it if you need to change the country code. This might be useful if you don't get the full speeds or can't see certain wireless channels.

The config looks ok. I might not be able to help with this. It should really just be a matter of plugging the card in the m.2 slot and connecting the usb cable.

**Comment by zearp** [comment] 2022-02-05 12:54
This is how it should look:

![Screenshot 2022-02-05 at 13 53 49](https://user-images.githubusercontent.com/63272687/152642965-75128db1-bedb-41de-a20f-d6070894aebe.png)

**Comment by zearp** [comment] 2022-02-05 12:55
Try to remove the HS07 block from the usb map and also make sure the onboard wireless and bluetooth settings are set to disabled in the bios.

**Comment by SeaDaddytheRed** [comment] 2022-02-05 12:58
Thank you for the reply.   I removed the HS07 block and have both the wireless and bluetooth disabled in the bios.  I think you are right in that the adapter is not working.  I just booted into Windows 11 and the wifi device was listed but no bluetooth device.  I tried moving the connector to both the USB headers with no luck.  The damn adapter took a month to get here from China and now I have to ask for a refund, or a replacement.  It's going to be a while!

**Comment by SeaDaddytheRed** [comment] 2022-02-05 13:00
I just noticed though that I removed the HS07 block in the usbports.kext info.plist but it is still listed in my Hackintool.

**Comment by zearp** [comment] 2022-02-05 13:05
Thats really annoying!

It is possible the tiny jst plug hasn't got all the wires clicked in properly. You can examine it closely, maybe one of the wires dislodged a bit from the plug in transit. 

If I were you I would check the wires carefully on both the card and the plug.

You can also try to wiggle it a bit while connected with Hackintool open, if it shows up it means there's an internal crack inside the wire and they need replacing. A local electronics shop might be able to solder on some new wires and attach a new jst plug for cheap. 

As for Hackintool, it remembers/caches the last results and doesn't remove anything on its own. You can select all ports and remove them from the list by clicking the large minus button and then press the refresh button for an up-to-date list.

**Comment by SeaDaddytheRed** [comment] 2022-02-05 13:09
Ah. thx for the mini lesson on the Hackintool.  I will closely examine the wires and keep trying.

**Comment by zearp** [comment] 2022-02-05 13:17
My guess and hope is the jst plug has some wires not fully seated. It is unlikely the usb part of the adapter isn't working while the pci part works fine. Most likely is either wires or plug.

Soldering on new wires isn't too difficult, the jst plug is difficult. It can be hard to find empty jst plugs and you'd also need a tool to fit tiny metal caps at the end of the wires and seat them into the plug.

It is annoying Intel decided to use these super small non-standard usb headers instead of normal ones. There is space enough for standard headers.

Good luck!

**Comment by zearp** [comment] 2022-02-06 02:02
I'm closing this issue as it isn't caused by the EFI but please keep me posted on any progress.

**Closed by zearp** 2022-02-06 02:02 UTC

**Comment by SeaDaddytheRed** [comment] 2022-02-06 03:26
I fiddled with the wires.  Tried reseating the card and looked at all the connections as close as I could but no luck.  Here are some up close pics of the adapter and connectors.

<a target="_blank" href="https://imageshack.com/i/poXBFd45j"><img src="https://imagizer.imageshack.com/v2/280x200q90/924/XBFd45.jpg" border="0"></a>
<a target="_blank" href="https://imageshack.com/i/pm7efmhlj"><img src="https://imagizer.imageshack.com/v2/280x200q90/922/7efmhl.jpg" border="0"></a>
<a target="_blank" href="https://imageshack.com/i/poSsc1Amj"><img src="https://imagizer.imageshack.com/v2/280x200q90/924/Ssc1Am.jpg" border="0"></a>

**Comment by zearp** [comment] 2022-02-07 00:25
The black wire soldering is a bit bad, but it looks like it's making contact. Have you tried booting up a Linux live distro and run the "lsusb" command? It will list any attached usb device regardless if it works or not. The same should happen in macOS or Windows though. If you have soldering iron you can try to fix the black wire's soldering. I can't tell if the wires are seated properly in the jst connector. Also check if the two internal ports are enabled in the bios.

![02](https://user-images.githubusercontent.com/63272687/152708113-534e7539-dd6d-4e5e-83ec-b90824b33d65.jpg)

I hope the seller will ship you a replacement because it seems either the cable is bad or less likely, some traces on the pcb are not good causing the usb part to not work. I ordered a bunch of these and only had 1 DOA, it did't work at all.

**Comment by SeaDaddytheRed** [comment] 2022-02-07 04:18
My BIOS looks exactly like yours. I have a digital microscope somewhere I can dig out and see if I can get a closer view of the jst connector.
I didn't have time to boot a linux distro at lunch today but here is my device manager in a fresh install of Windows 11.  I installed the wifi and bluetooth drivers from bootcamp so the wifi is working but yeah, there is no entry for bluetooth.  Could it be one of the other devices with the yellow marks?

<a href="https://imgbox.com/VoMWplu6" target="_blank"><img src="https://thumbs2.imgbox.com/90/c5/VoMWplu6_t.png" alt="image host"/></a>

I messaged the seller but haven't received a reply yet.

**Comment by SeaDaddytheRed** [comment] 2022-02-08 00:53
I loaded up Mint and lsusb.  I will send the seller these pics and just wait and see.

<a href="https://imgbox.com/P804ImKi" target="_blank"><img src="https://thumbs2.imgbox.com/cf/8b/P804ImKi_t.jpeg" alt="image host"/></a>

<a href="https://imgbox.com/4xdGY3ji" target="_blank"><img src="https://thumbs2.imgbox.com/67/63/4xdGY3ji_t.jpeg" alt="image host"/></a>

Thank you for all the effort.  I will update this post in a few weeks, or whenever the seller responds, and let you know what happens.  I just hope it's the adapter or the card and not my NUC.

**Comment by zearp** [comment] 2022-02-08 12:31
You would have to be really unlucky to receive a NUC with two broken internal usb headers.

**Comment by SeaDaddytheRed** [comment] 2022-03-05 13:55
Well, I received another adapter today from China.  I successfully got a refund on the first one.
But, it still doesn't work.
Nothing has changed.  Still no bluetooth device in Windows, Mac, or Linux.

With the adapter narrowed out I am going to try replacing the wifi card.  Luckily I found a BCM94360CS2 cheap on a used site here. I will get it by next week sometime.

**Comment by SeaDaddytheRed** [comment] 2022-03-09 05:02
Okay.  So I now have two adapters and two BCM94360CS2 cards.  No combination of these cards and adapters gives me a bluetooth device.  I am using my Windows install to check since I don't want to screw up my mac install.  There is no unknown or bluetooth device listed in Device Manager.

I am at a loss.  My last idea is to disconnect the CMOS battery and clear the BIOS but that means taking the motherboard out of my Akasa case and re-applying thermal paste.

**Comment by SeaDaddytheRed** [comment] 2022-03-09 09:56
I took out the motherboard and unplugged the CMOS battery for about 10 minutes while I reapplied thermal paste.  Put it all back together, defaulted the BIOS, then set all the right toggles for macOS but still no good.

Just out of curiosity does your adapters say version 2.0 or 3.0 on them?  Both mine say 3.0 and the one in your picture linked says 2.0.  Also, do you have a recommendation for a different combo card I could try out with these adapters?

**Comment by SeaDaddytheRed** [comment] 2022-04-10 09:15
Hello,

So I received another adapter finally from China.  This is a completely different one from a different company.

![51wpHyf2sxL _AC_SL1024_](https://user-images.githubusercontent.com/77227142/162611247-434595ba-5ac9-481b-90d6-db50042aacaa.jpg)

And everything works!  All the continuity stuff works.  The wifi and bluetooth have a strong single.

I guess the lesson is the new version of the NUC adapters sold on Aliexpress are not good, or I have extremely bad luck and got two bad adapters.

Thanks for your help and your continued support for macos on the NUC8!

**Comment by gtrooper** [comment] 2022-04-10 12:40
Hello ! Could you please share the name of the adapter you bought ? I need to know the exact model so that I can give it a try ! Thank you, in advanced !

**Comment by SeaDaddytheRed** [comment] 2022-04-10 13:59
Here is the [link](https://www.amazon.co.jp/-/en/gp/product/B09KPSTNVM/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1).  I am in Japan so I bought it on Amazon Japan.  I cannot seem to find a model number.

**Comment by zearp** [comment] 2022-04-10 23:07
I'm happy it works! Looks like a great complete kit. Thanks for updating and sharing.

**Comment by chepe263** [comment] 2023-03-22 16:56
I wanted to mention that the mini 1.25mm jst pitch connector has two uses, for usb (at the bottom of the board, there are two of them) and for sata power (at the side of the nvme connector). You need to be careful for this (I wasn't) and It took several weeks later to find out the right connector.

Please check the [technical documentation](https://www.intel.com/content/dam/support/us/en/documents/mini-pcs/nuc-kits/NUC8i3BE_NUC8i5BE_NUC8i7BE_TechProdSpec.pdf), page 31.

This is a photo from [a few posts above](https://imgbox.com/4xdGY3ji) in case your missed it. I did miss it.
