### ISSUE TITLE
Install Loop

### ISSUE THREAD

**Issue by BennYCruger** [zearp/Nucintosh#56] opened 2021-07-22 17:26 UTC
Hi.

It just keeps looping into the recovery apple screen after the Big Sur Download.

**Comment by zearp** [comment] 2021-07-22 18:32
It sounds like you're updating to the new Big Sur release form within Big Sur and get stuck in a reboot loop? Can you provide more information?

I've not yet tried the new Big Sur 11.5 release so maybe something in there breaks something. For now you can try setting ```SecureBootModel``` to ```Disabled``` and see if that helps. Since beta 2 of Monterey this is needed so maybe this also needed for the new Big Sur release.

**Comment by zearp** [comment] 2021-07-22 19:54
I'm currently updating my Big Sur install on my test NUC from 11.4 to 11.5, I do have ```SecureBootModel``` set to ```Disabled``` on it because it also has Monterey installed.

I updated from within macOS in ```Software Update``` not with a full installer or the installer app. Sometimes the latter is needed but shouldn't be needed for updates within a major macOS release like updating 11.4 to 11.5.

It has rebooted a few times but not stuck in a loop so far, it shows 9 minutes remaining. Will update here in a while to share the results.

**Comment by zearp** [comment] 2021-07-22 20:14
Update installed ok for me, no (boot) loops. I'm not sure if it was ```SecureBootModel``` or maybe it was a fixed in recent kexts or OpenCore updates. I'm running the current version from the repo not a release. I might update the release later, till then you can download a [.zip](https://github.com/zearp/Nucintosh/archive/refs/heads/master.zip) version of the whole repo and take the EFI from there.

**Comment by zearp** [comment] 2021-07-23 04:04
Updated another NUC from 11.4 to 11.5 using ```Software Update``` -- this one had ```SecureBootModel``` set to Macmini8,1 and it went fine as well. I noticed on the first NUC it rebooted more often than on the other one. Maybe it wasn't looping but needed more reboots than expected?

Closing this for now because I can't reproduce, try again with your EFI updated (clear nvram for good measure) and try to catch the error where it reboots. Filming the boot process with a phone and then scrolling the timeline to find where it reboots will show what happens. Let me know what kind of errors and warnings scroll by right before it reboots.

**Closed by zearp** 2021-07-23 04:04 UTC
Labels: can't reproduce

**Comment by BennYCruger** [comment] 2021-07-23 06:24
It boots fine and does the install…

Then it loops back into this screen.

Do you have a place where i can download the 11.4dmg?

![IMG_5824](https://user-images.githubusercontent.com/60181661/126744561-e02c952a-3eb7-40de-8faf-928cd4318757.jpg)
![IMG_5823](https://user-images.githubusercontent.com/60181661/126744574-88e942ac-6c78-4835-a2b8-3660f9af3752.jpg)
![unnamed](https://user-images.githubusercontent.com/60181661/126744579-8137275d-1ea7-4ca2-8ec3-4277e72dc355.jpg)

**Comment by zearp** [comment] 2021-07-23 12:08
Sometimes you manually have to select the correct entry from the menu to continue the install from the correct disk 

You only boot once into the installer, you format the disk and the installer copies everything it needs to the internal disk. 

From that point you should always boot to the internal disk. Check the menu and select the correct entry cuz it doesn’t always automatically selects it.
