### ISSUE TITLE
[NUC8i5BEH] - macOS 12 beta 2 no bluetooth

### ISSUE THREAD

**Issue by ecklf** [zearp/Nucintosh#55] opened 2021-07-11 18:37 UTC
Sadly not having any bluetooth after fresh install. It displays as on but doesn't start searching for anything.

![image](https://user-images.githubusercontent.com/8146736/125206447-a0225900-e287-11eb-9863-3a11ba6dd689.png)

Hackintool:

![image](https://user-images.githubusercontent.com/8146736/125206466-c2b47200-e287-11eb-9d4a-4b045f89947e.png)

Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
  - apply suggested Monterey changes in the README (removing `IntelBluetoothInjector.kext` and adding `BlueToolFixup.kext`)
- macOS version and optionally the build number
  - macOS 12 beta 2 
- Any changes you made to the config and/or EFI other than serials/etc
  - above steps and upgrading to latest open core

**Comment by zearp** [comment] 2021-07-11 18:46
I can't reproduce this on my NUC running beta 2. Bluetooth works fine. Can you post your config.plist?

**Comment by zearp** [comment] 2021-07-11 18:50
![bt](https://user-images.githubusercontent.com/63272687/125206831-75d19b00-e289-11eb-9049-8789ccc54c17.png)

I just paired a mouse to test and it does work for me. What made you conclude it isn't working? Can't see devices that are in pairing mode?

**Comment by zearp** [comment] 2021-07-11 18:58
> upgrading to latest open core

What exactly does that entail? The OpenCore and kexts build on the repo are very up-to-date, newer than any release version from the official repo's cuz I build form source. Chances are if you mix up release versions of kexts/OpenCore with things form the repo you can issues cuz things can be fixed or changes that depend on other changes. Iv'e had a similar issue the other day.

Someone "updated" the kexts but in fact downgraded them breaking other parts of the chain is it depended on things not found in the release version he "upgrades" to. If you do these kind of things you have to "upgrade" everything, all kexts and all OpenCore parts.

I also can't really help if things are changed compared to my repo cuz I won't be running the same versions and such. Try the latest EFI by cloning the repo, or download the one I've attached here.

[EFI.zip](https://github.com/zearp/Nucintosh/files/6797502/EFI.zip)

I'm running above EFI on my Monterey test NUC.

**Comment by zearp** [comment] 2021-07-11 19:09
> upgrading to latest open core

What exactly does that entail? The OpenCore and kexts build on the repo are very up-to-date, newer than any release version from the official repo's cuz I build from the latest sources. Chances are if you mix up release versions of kexts/OpenCore with things from the repo you get weird issues cuz fixes/changes can depend on other changes not found the release version or the other way around. I've had a similar issue the other day.

Someone "updated" the kexts but in fact downgraded them, breaking other parts of the chain. Things kexts on the repo depend on where not found yet in the release version he "upgraded" with. Causing problems. If you do these kind of things you have to "upgrade" everything, all kexts and all OpenCore parts. Mixing up release versions with newer builds can lead to very strange problems.

I also can't really help if things are changed compared to my repo cuz I won't be running the same versions and such. Try the latest EFI by cloning the repo, or download the one I've attached here.

[EFI-Monterey.zip](https://github.com/zearp/Nucintosh/files/6797508/EFI-Monterey.zip)

I'm running above EFI on my Monterey test NUC.

**Comment by ecklf** [comment] 2021-07-11 19:15
> What made you conclude it isn't working? Can't see devices that are in pairing mode?
It was taking ages to load and have no loading spinner / show any of my Bluetooth devices.

> What exactly does that entail
I didn't see the used OC version documented anywhere in this repo.

I kept all the kexts as is (also downloaded the Monterey kext from the README link). Just tried using `BlueTool` / `IntelBluetoothFirmware` kexts from the GitHub releases which seems to have fixed my issue.

**Comment by zearp** [comment] 2021-07-11 19:41
I'm glad it's fixed but I don't know what happened that made it not work in the first place. Just be mindful when you update things cuz it might not be an update. If you must run the vert latest bleeding edge versions, I suggest you use the Dortania build site where they have new builds every single time one of the repo's they follow gets a commit. 

As for issues on my repo, I can only help if people use the EFI unmodified, the only changes should be the serials and such. I can't reliably reproduce issues if people run different versions of OpenCore or kexts from me. No matter how minor it is not good for troubleshooting. I always compile all the parts in one go so they always work together.

The current builds on the repo are 16 hours old. The only commits to OpenCore and the kexts that are missing and the ones newer than 16 hours. Tomorrow I will zip it up and make a release of it, trying to do that every Monday or whenever needed. Either way your problem is solved so I'll close this issue.

Let me know if you run into trouble again!

**Closed by zearp** 2021-07-11 19:41 UTC

**Comment by ecklf** [comment] 2021-07-12 03:59
Gotcha. Thanks for the quick response ☺️
