### ISSUE TITLE
HDMI 4K display sometime snowflake

### ISSUE THREAD

**Issue by neatguo** [zearp/Nucintosh#11] opened 2020-11-19 07:33 UTC
I have two AOC 4k displays,one used Thunderbolt，the other used HDMI port.
- AOC 4k display used HDMI port, When started NUC8i5Beh, sometime snowflakes appear. The Thunderbolt port is fine.
- Locked screen. When the monitor is off without signal，Wakeup the NUC8i5Beh,HDMI port still no signal. The Thunderbolt port is fine.

**Comment by zearp** [comment] 2020-11-19 11:57
I also have snowflakes in other builds sometimes when they’re connected to a tv. It lasts a second before it returns to normal. I don’t think there is anything you can do about this. I’ve had it happen on multiple builds. Not really an issue for me since the picture returns to normal within seconds.

For the locked screen I have no clue what could cause it. But you can try adding the force online property in the frame buffer section. It fixes most instances where screens don’t wake up properly and it may also help reduce the snowflakes. Another thing you can try is removing the connector patches in the frame buffer config. It may work better without those. I have no 4K usb-c or Thunderbolt screens to test with.

Let me know how it goes.

**Comment by zearp** [comment] 2020-11-19 12:31
Try this config with the connector patches removed and force-online added. It's tricky to make a config that would work for everybody cuz I don't have the equipment to test things like Thunderbolt displays or dual 4k screens. I only have 1080p DP/HDMI screens to test with.

[config.plist.zip](https://github.com/zearp/Nucintosh/files/5566715/config.plist.zip)

**Comment by neatguo** [comment] 2020-11-20 15:35
Thanks.
I have tried the force-online.
But not works.

**Comment by zearp** [comment] 2020-11-20 15:45
I can't reproduce the snowflakes on my NUC but I do sometimes get snowflakes on my Dell thats connected to the tv. But only after it wakes up and it only lasts for a little while.

Your snowflakes last and don't go away?

**Comment by neatguo** [comment] 2020-11-21 16:05
When the NUC is started, snowflakes sometimes appear on HDMI port. Not every time.

**Comment by zearp** [comment] 2020-11-22 13:18
It's hard to troubleshoot when it doesn't happen every time. I face the same issue on my Dell thats connected to my tv. sometimes after wake up I get the snow, most of time I don't. I have no idea what this is caused by. My best guess would be WhateverGreen.

My best suggestion would be to check their documentation and especially the parts with boot flags and options like force-online. Maybe some flag can help here. The thing is that it will be hard to test since it doesn't happen every time. You'll have to be very dedicated and patient.

It would be nice if you can find a way to reproduce the issue so it always gives you the snow when you do Z or Y. That way it will become a lot easier to test if a flag or option works. I assume you've tried different cables, though I doubt its the cable since its an intermittent issue.

I'll close this for now but please post again if you have any news or progress.

**Closed by zearp** 2020-11-22 13:18 UTC
